"""phase_2_updates

Revision ID: 230fa779a978
Revises: dfc1d4304168
Create Date: 2026-09-11 00:12:01.874035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230fa779a978'
down_revision: Union[str, None] = 'dfc1d4304168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Data migration: convert lowercase states to uppercase to satisfy new constraints
    op.execute("UPDATE campaigns SET status = 'DRAFT' WHERE status = 'draft'")
    op.execute("UPDATE campaigns SET status = 'RUNNING' WHERE status = 'running'")
    op.execute("UPDATE campaigns SET status = 'PAUSED' WHERE status = 'paused'")
    op.execute("UPDATE campaigns SET status = 'CANCELLED' WHERE status = 'stopped'")
    op.execute("UPDATE campaigns SET status = 'COMPLETED' WHERE status = 'completed'")
    
    op.execute("UPDATE campaign_contacts SET status = 'PENDING' WHERE status = 'pending'")
    op.execute("UPDATE campaign_contacts SET status = 'SENT' WHERE status = 'sent'")
    op.execute("UPDATE campaign_contacts SET status = 'FAILED' WHERE status = 'failed'")
    op.execute("UPDATE campaign_contacts SET status = 'SKIPPED' WHERE status = 'skipped'")

    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    if is_sqlite:
        with op.batch_alter_table('app_settings', schema=None) as batch_op:
            batch_op.create_unique_constraint('uq_setting_key', ['key'])

    with op.batch_alter_table('campaign_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclusion_reason', sa.String(), nullable=True))
        # Handle check constraint update
        batch_op.drop_constraint('ck_cc_status', type_='check')
        batch_op.create_check_constraint(
            'ck_cc_status',
            sa.text("status IN ('PENDING','ELIGIBLE','EXCLUDED','QUEUED','SENT','FAILED','SKIPPED')")
        )

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        if is_sqlite:
            batch_op.create_unique_constraint('uq_campaign_name', ['name'])
        # Handle check constraint update
        batch_op.drop_constraint('ck_campaign_status', type_='check')
        batch_op.create_check_constraint(
            'ck_campaign_status',
            sa.text("status IN ('DRAFT','SCHEDULED','RUNNING','PAUSED','COMPLETED','CANCELLED','FAILED')")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint('ck_campaign_status', type_='check')
        batch_op.create_check_constraint(
            'ck_campaign_status',
            sa.text("status IN ('draft','running','paused','stopped','completed')")
        )
        if is_sqlite:
            batch_op.drop_constraint('uq_campaign_name', type_='unique')

    with op.batch_alter_table('campaign_contacts', schema=None) as batch_op:
        batch_op.drop_constraint('ck_cc_status', type_='check')
        batch_op.create_check_constraint(
            'ck_cc_status',
            sa.text("status IN ('pending','sent','failed','skipped')")
        )
        batch_op.drop_column('exclusion_reason')

    if is_sqlite:
        with op.batch_alter_table('app_settings', schema=None) as batch_op:
            batch_op.drop_constraint('uq_setting_key', type_='unique')

    op.execute("UPDATE campaigns SET status = 'draft' WHERE status = 'DRAFT'")
    op.execute("UPDATE campaigns SET status = 'running' WHERE status = 'RUNNING'")
    op.execute("UPDATE campaigns SET status = 'paused' WHERE status = 'PAUSED'")
    op.execute("UPDATE campaigns SET status = 'stopped' WHERE status = 'CANCELLED'")
    op.execute("UPDATE campaigns SET status = 'completed' WHERE status = 'COMPLETED'")
    op.execute("UPDATE campaigns SET status = 'draft' WHERE status = 'SCHEDULED'")
    op.execute("UPDATE campaigns SET status = 'failed' WHERE status = 'FAILED'")
    
    op.execute("UPDATE campaign_contacts SET status = 'pending' WHERE status IN ('PENDING', 'ELIGIBLE', 'QUEUED')")
    op.execute("UPDATE campaign_contacts SET status = 'sent' WHERE status = 'SENT'")
    op.execute("UPDATE campaign_contacts SET status = 'failed' WHERE status = 'FAILED'")
    op.execute("UPDATE campaign_contacts SET status = 'skipped' WHERE status IN ('SKIPPED', 'EXCLUDED')")


    # ### end Alembic commands ###
