"""phase_3_queue_and_batches

Revision ID: 7e6cba6d608e
Revises: 230fa779a978
Create Date: 2026-09-11 12:01:55.435625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6cba6d608e'
down_revision: Union[str, None] = '230fa779a978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create campaign_batches table
    op.create_table('campaign_batches',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('batch_number', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False, server_default='PENDING'),
        sa.Column('total_items', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('processed_items', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('successful_items', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('failed_items', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('PENDING','IN_PROGRESS','PAUSED','COMPLETED','CANCELLED')", name='ck_batch_status'),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('campaign_id', 'batch_number', name='uq_campaign_batch_number')
    )
    with op.batch_alter_table('campaign_batches', schema=None) as batch_op:
        batch_op.create_index('idx_campaign_batches_campaign_id', ['campaign_id'], unique=False)
        batch_op.create_index('idx_campaign_batches_status', ['status'], unique=False)

    # 2. Data migration on messages before altering constraints
    op.execute("UPDATE messages SET status = 'QUEUED' WHERE status = 'queued'")
    op.execute("UPDATE messages SET status = 'PROCESSING' WHERE status = 'sending'")
    op.execute("UPDATE messages SET status = 'SENT' WHERE status = 'sent'")
    op.execute("UPDATE messages SET status = 'FAILED' WHERE status = 'failed'")
    op.execute("UPDATE messages SET status = 'SKIPPED' WHERE status = 'skipped'")
    op.execute("UPDATE messages SET status = 'RETRY_PENDING' WHERE status = 'retried'")

    # 3. Batch alter messages table
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_contact_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sequence_number', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('idempotency_key', sa.String(128), nullable=True))
        batch_op.add_column(sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('max_attempts', sa.Integer(), nullable=False, server_default='3'))
        batch_op.add_column(sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('error_type', sa.String(32), nullable=True))
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('locked_by', sa.String(64), nullable=True))

        # Update check constraint
        batch_op.drop_constraint('ck_message_status', type_='check')
        batch_op.create_check_constraint(
            'ck_message_status',
            sa.text("status IN ('PENDING','QUEUED','PROCESSING','SENT','FAILED','RETRY_PENDING','CANCELLED','SKIPPED')")
        )
        batch_op.create_index('idx_messages_idempotency_key', ['idempotency_key'], unique=False)
        batch_op.create_index('idx_messages_next_retry_at', ['next_retry_at'], unique=False)
        batch_op.create_unique_constraint('uq_messages_idempotency_key', ['idempotency_key'])
        batch_op.create_foreign_key('fk_messages_batch_id', 'campaign_batches', ['batch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_messages_campaign_contact_id', 'campaign_contacts', ['campaign_contact_id'], ['id'], ondelete='CASCADE')

    # Assign default idempotency keys for existing messages if any
    op.execute("UPDATE messages SET idempotency_key = 'msg_' || id || '_legacy' WHERE idempotency_key IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE messages SET status = 'queued' WHERE status IN ('QUEUED', 'PENDING')")
    op.execute("UPDATE messages SET status = 'sending' WHERE status = 'PROCESSING'")
    op.execute("UPDATE messages SET status = 'sent' WHERE status = 'SENT'")
    op.execute("UPDATE messages SET status = 'failed' WHERE status = 'FAILED'")
    op.execute("UPDATE messages SET status = 'skipped' WHERE status IN ('SKIPPED', 'CANCELLED')")
    op.execute("UPDATE messages SET status = 'retried' WHERE status = 'RETRY_PENDING'")

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_campaign_contact_id', type_='foreignkey')
        batch_op.drop_constraint('fk_messages_batch_id', type_='foreignkey')
        batch_op.drop_constraint('uq_messages_idempotency_key', type_='unique')
        batch_op.drop_index('idx_messages_next_retry_at')
        batch_op.drop_index('idx_messages_idempotency_key')
        batch_op.drop_constraint('ck_message_status', type_='check')
        batch_op.create_check_constraint(
            'ck_message_status',
            sa.text("status IN ('queued','sending','sent','failed','skipped','retried')")
        )
        batch_op.drop_column('locked_by')
        batch_op.drop_column('locked_at')
        batch_op.drop_column('error_type')
        batch_op.drop_column('next_retry_at')
        batch_op.drop_column('last_attempt_at')
        batch_op.drop_column('max_attempts')
        batch_op.drop_column('attempt_count')
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('sequence_number')
        batch_op.drop_column('batch_id')
        batch_op.drop_column('campaign_contact_id')

    with op.batch_alter_table('campaign_batches', schema=None) as batch_op:
        batch_op.drop_index('idx_campaign_batches_status')
        batch_op.drop_index('idx_campaign_batches_campaign_id')

    op.drop_table('campaign_batches')
    # ### end Alembic commands ###
