"""initial_schema

Revision ID: dfc1d4304168
Revises: 
Create Date: 2026-09-10 23:19:45.525734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc1d4304168'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('key', name='uq_setting_key')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('min_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('max_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('batch_pause_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_threshold', sa.Integer(), nullable=False),
    sa.Column('element_wait_timeout', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','running','paused','stopped','completed')", name='ck_campaign_status'),
    sa.CheckConstraint('batch_pause_seconds >= 0', name='ck_batch_pause_min'),
    sa.CheckConstraint('batch_size >= 1', name='ck_batch_size_min'),
    sa.CheckConstraint('daily_limit >= 1', name='ck_daily_limit_min'),
    sa.CheckConstraint('element_wait_timeout BETWEEN 5 AND 60', name='ck_element_wait_timeout_range'),
    sa.CheckConstraint('error_threshold >= 1', name='ck_error_threshold_min'),
    sa.CheckConstraint('max_delay_seconds >= 1', name='ck_max_delay_min'),
    sa.CheckConstraint('max_retries BETWEEN 0 AND 10', name='ck_max_retries_range'),
    sa.CheckConstraint('min_delay_seconds >= 1', name='ck_min_delay_min'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_campaign_name')
    )
    op.create_index('idx_campaigns_status', 'campaigns', ['status'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_e164', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('consent_status', sa.String(), nullable=False),
    sa.Column('opted_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('messages_sent_count', sa.Integer(), nullable=False),
    sa.Column('contact_status', sa.String(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("consent_status IN ('pending','opted_in','opted_out')", name='ck_consent_status'),
    sa.CheckConstraint("contact_status IN ('active','inactive','duplicate')", name='ck_contact_status'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_e164', 'country_code', name='uq_contact_phone_country')
    )
    op.create_index('idx_contacts_consent_status', 'contacts', ['consent_status'], unique=False)
    op.create_index('idx_contacts_contact_status', 'contacts', ['contact_status'], unique=False)
    op.create_index('idx_contacts_country_code', 'contacts', ['country_code'], unique=False)
    op.create_index('idx_contacts_phone_e164', 'contacts', ['phone_e164'], unique=False)
    op.create_table('campaign_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skip_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','sent','failed','skipped')", name='ck_cc_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contact_id', name='uq_campaign_contact')
    )
    op.create_index('idx_cc_campaign_id', 'campaign_contacts', ['campaign_id'], unique=False)
    op.create_index('idx_cc_contact_id', 'campaign_contacts', ['contact_id'], unique=False)
    op.create_index('idx_cc_status', 'campaign_contacts', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('rendered_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('queued','sending','sent','failed','skipped','retried')", name='ck_message_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_campaign_id', 'messages', ['campaign_id'], unique=False)
    op.create_index('idx_messages_contact_id', 'messages', ['contact_id'], unique=False)
    op.create_index('idx_messages_status', 'messages', ['status'], unique=False)
    op.create_table('send_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('messages_failed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active','completed','error','stopped')", name='ck_send_session_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_send_sessions_campaign_id', 'send_sessions', ['campaign_id'], unique=False)
    op.create_index('idx_send_sessions_status', 'send_sessions', ['status'], unique=False)
    op.create_table('unsubscribes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('keyword_matched', sa.String(), nullable=True),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmation_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', name='uq_unsubscribe_contact')
    )
    op.create_index('idx_unsubscribes_contact_id', 'unsubscribes', ['contact_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_campaign_id', 'audit_logs', ['campaign_id'], unique=False)
    op.create_index('idx_audit_logs_contact_id', 'audit_logs', ['contact_id'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    # ### end Alembic commands ###
    
    # Seed app_settings with defaults
    op.execute(
        "INSERT INTO app_settings (key, value, description, updated_at) VALUES "
        "('GLOBAL_DAILY_LIMIT', '100', 'Maximum messages per calendar day', CURRENT_TIMESTAMP), "
        "('APP_TIMEZONE', 'Africa/Cairo', 'IANA timezone for date boundaries', CURRENT_TIMESTAMP), "
        "('LOG_LEVEL', 'INFO', 'Application logging level', CURRENT_TIMESTAMP)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_logs_event_type', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_contact_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_campaign_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_unsubscribes_contact_id', table_name='unsubscribes')
    op.drop_table('unsubscribes')
    op.drop_index('idx_send_sessions_status', table_name='send_sessions')
    op.drop_index('idx_send_sessions_campaign_id', table_name='send_sessions')
    op.drop_table('send_sessions')
    op.drop_index('idx_messages_status', table_name='messages')
    op.drop_index('idx_messages_contact_id', table_name='messages')
    op.drop_index('idx_messages_campaign_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_cc_status', table_name='campaign_contacts')
    op.drop_index('idx_cc_contact_id', table_name='campaign_contacts')
    op.drop_index('idx_cc_campaign_id', table_name='campaign_contacts')
    op.drop_table('campaign_contacts')
    op.drop_index('idx_contacts_phone_e164', table_name='contacts')
    op.drop_index('idx_contacts_country_code', table_name='contacts')
    op.drop_index('idx_contacts_contact_status', table_name='contacts')
    op.drop_index('idx_contacts_consent_status', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('idx_campaigns_status', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
