"""
Operational event taxonomy constants for WhatsApp Outreach Automation.

Standardized operational events emitted across subsystems to structured JSON logs.
"""

from enum import Enum


class EventType(str, Enum):
    # System & Lifecycle
    SYSTEM_STARTUP = "SYSTEM_STARTUP"
    SYSTEM_SHUTDOWN = "SYSTEM_SHUTDOWN"
    PREFLIGHT_CHECK_PASSED = "PREFLIGHT_CHECK_PASSED"
    PREFLIGHT_CHECK_FAILED = "PREFLIGHT_CHECK_FAILED"

    # Runner Process Lifecycle
    RUNNER_STARTING = "RUNNER_STARTING"
    RUNNER_STARTED = "RUNNER_STARTED"
    RUNNER_HEARTBEAT = "RUNNER_HEARTBEAT"
    RUNNER_IDLE = "RUNNER_IDLE"
    RUNNER_PAUSED = "RUNNER_PAUSED"
    RUNNER_STOPPING = "RUNNER_STOPPING"
    RUNNER_STOPPED = "RUNNER_STOPPED"
    RUNNER_FAILED = "RUNNER_FAILED"

    # Process Lock & Host Concurrency
    PROCESS_LOCK_ACQUIRED = "PROCESS_LOCK_ACQUIRED"
    PROCESS_LOCK_CONFLICT = "PROCESS_LOCK_CONFLICT"
    PROCESS_LOCK_RELEASED = "PROCESS_LOCK_RELEASED"
    STALE_METADATA_RECOVERED = "STALE_METADATA_RECOVERED"

    # Campaign Domain
    CAMPAIGN_STATE_TRANSITION = "CAMPAIGN_STATE_TRANSITION"

    # Queue State Machine & Dispatch
    QUEUE_CLAIM_SUCCESS = "QUEUE_CLAIM_SUCCESS"
    STALE_LEASE_RECOVERED = "STALE_LEASE_RECOVERED"
    MESSAGE_SEND_CONFIRMED = "MESSAGE_SEND_CONFIRMED"
    MESSAGE_TEMPORARY_FAILURE = "MESSAGE_TEMPORARY_FAILURE"
    MESSAGE_PERMANENT_FAILURE = "MESSAGE_PERMANENT_FAILURE"
    MESSAGE_UNKNOWN_OUTCOME = "MESSAGE_UNKNOWN_OUTCOME"
    MESSAGE_MANUAL_OVERRIDE = "MESSAGE_MANUAL_OVERRIDE"

    # Provider & Session Lifecycle
    PROVIDER_CONNECTED = "PROVIDER_CONNECTED"
    PROVIDER_HEALTH_CHECK_FAIL = "PROVIDER_HEALTH_CHECK_FAIL"
    SESSION_AUTHENTICATING = "SESSION_AUTHENTICATING"
    SESSION_CONNECTED = "SESSION_CONNECTED"
    SESSION_LOST = "SESSION_LOST"

    # Reliability Controls
    CIRCUIT_BREAKER_TRIPPED = "CIRCUIT_BREAKER_TRIPPED"
    CIRCUIT_BREAKER_RESET = "CIRCUIT_BREAKER_RESET"
    EMERGENCY_STOP_ACTIVATED = "EMERGENCY_STOP_ACTIVATED"
    EMERGENCY_STOP_RESUMED = "EMERGENCY_STOP_RESUMED"
